name: build
on:
    push:
        branches: [main]
        paths-ignore: ["README.md", "cli/**"]
    pull_request:
        branches: [main]
        paths-ignore: ["README.md", "cli/**"]
    workflow_dispatch:
jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - run: make release
